### ISSUE TITLE
What should go into argument_list variable?

### ISSUE THREAD

**Issue by josephmje** [MASILab/Synb0-DISCO#1]
Hi,

I'm trying to set up this package in my lab. I was confused about what should go in the `<argument_list>` when running `run_synb0_run.sh`. Is there any documentation for this?

Thanks

**Comment by hanscol** [comment]
I apologize for the lack of a readme, this work was always intended to be a docker which you can find at hansencb/synb0-disco on docker hub. run_synb0_run.sh expects a path to a matlab compiler runtime for 2018a. It also expects a file /INPUTS/T1.nii.gz and a directory /OUTPUTS to exist, which makes more sense in the docker. I would suggest visiting the docker hub page and see if that clears anything up.

**Comment by josephmje** [comment]
Thank you @hanscol ! Would you happen to have the Dockerfile used to create the container as well?

**Comment by hanscol** [comment]
I've attached the docker file, though the Matlab runtime file and the fsl build are not included in this repository. I think there is a bug in the docker that tries to source the fsl path within the script, but the dockerfile adds it to the path correctly and fsl was copied to the docker.

[Dockerfile.txt](https://github.com/MASILab/Synb0-DISCO/files/3234609/Dockerfile.txt)

**Comment by josephmje** [comment]
Ahhh k. Thank you! I was confused about the FSL warnings after running the docker but the output seems to be ok.
