### ISSUE TITLE
Adapting the Synb0 disco pipeline for Feline data

### ISSUE THREAD

**Issue by archithrajan711** [MASILab/Synb0-DISCO#14]
Hi Experts,

I have some feline data which is heavily distorted in the L-R direction and without a reverse b0 acquisition, on which I'd like to run the pipeline.

1. To start off with, would this be even feasible considering the model was trained on human brain data? 

2. If there's a chance, what modifications would one need to perform, especially in the steps where non-linear registrations to MNI templates have been performed?I do have a few Feline templates if that could be of any use.

Regards,
Archith

**Comment by hanscol** [comment]
Hello Archith,

Unfortunately, we have no reason to believe the model will generalize to other species, though we have not tried. If you still want to run the model on your data, you could run the docker interactively with bash as your entrypoint and then follow the steps in our pipeline as close as possible. 

Best,
Colin

**Comment by schillkg** [comment]
Hi Archith,

Like Colin said - I'm aren't sure if this will generalize to non human data, but it is worth a shot! If you do give it a run, I would be happy to walk through the results and we can debug where the algorithm may first go wrong (my guess is that it might have a hard time synthesizing the non-distorted data). Regardless, I'm excited to see what it does. Modifications may be needed in the registration to standard space, and maybe a contrast normalization (to make a structural image look "T1w"), as well as manipulation of TOPUP configuration file, but it is still possible it may work right out of the box. 

Thank you,
Kurt

**Comment by archithrajan711** [comment]
Dear Colin and Kurt,
Thank you for the replies.I'll give it a try and get back soon.

Warm Regards,
Archith

**Comment by archithrajan** [comment]
Dear Colin and Kurt,

Sorry for the very very late reply. As far as I could remember, the earlier data did not work well, and then the data itself was lost before I shifted workplace. I might soon encounter some more of similar data and hence piggybacking on this post, for a couple of queries:
1.Wanted to ask, if something like, say tranfer learning could be applied to tune the model for non-human datasets?

2.Also, on an unrelated/distantly related note, would the model generalize well in diseases like GBMs,where there's a considerable abberation in the normal brain anatomy?Although anatomical features are preserved across the modalities(T1 and b0), should one still be careful, especially in phenomenon like mid-line shifts?

Thanks and Regards,
Archith
