### ISSUE TITLE
image exception #75

### ISSUE THREAD

**Issue by SabreA7** [MASILab/Synb0-DISCO#15]
Hi Team, 

I have come across the following error  (image exception #75) when Synb0 is running the epi_reg. I was wondering how I can go about fixing this? 

Removing job directory...
Skull stripping T1
bet /INPUTS/T1.nii.gz /tmp/tmp.2mt3dWD5dv/T1_mask.nii.gz -R

epi_reg distorted b0 to T1
epi_reg --epi=/INPUTS/b0.nii.gz --t1=/INPUTS/T1.nii.gz --t1brain=/tmp/tmp.2mt3dWD5dv/T1_mask.nii.gz --out=/tmp/tmp.2mt3dWD5dv/epi_reg_d
Running FAST segmentation
FLIRT pre-alignment
Running BBR
Image Exception : #75 :: 3D only method called by higher-dimensional volume.
3D only method called by higher-dimensional volume.
Could not open matrix file /tmp/tmp.2mt3dWD5dv/epi_reg_d.mat
/extra/fsl/bin/epi_reg: line 399: 85972 Segmentation fault      $FSLDIR/bin/applywarp -i ${vepi} -r ${vrefhead} -o ${vout} --premat=${vout}.mat --interp=spline

Cheers
-------

**Comment by hanscol** [comment]
I'm pretty sure that this error comes up when you use a 4D volume when epi_reg is expecting a 3D volume. My guess is that your b0 image is not just a single b0.

**Comment by SabreA7** [comment]
I had merged my b0's and i think this is what was causing the issue. i have now run it using a single b0 image and it has worked. Thank you for your help.
