### ISSUE TITLE
b0_topup.nii.gz not created 

### ISSUE THREAD

**Issue by SabreA7** [MASILab/Synb0-DISCO#19]
Hi, 

I have run Synb0 without any errors coming up, however from the output data I seem to be missing the b0_topup.nii.gz file? I am at a loss.  Is this file required for running Eddy? 

<img width="384" alt="Screen Shot 2021-03-14 at 9 45 26 AM" src="https://user-images.githubusercontent.com/79776758/111051970-1619dd80-84ab-11eb-96c9-1cad5f40ff51.png">

Cheers,

**Comment by hanscol** [comment]
That is a typo on our part. The pipeline only creates the b0_all_topup.nii.gz file, so this output looks correct.

**Comment by SabreA7** [comment]
Thank you so much!
