### ISSUE TITLE
What version of pix2pix is this dependent on?

### ISSUE THREAD

**Issue by salimansourc** [MASILab/Synb0-DISCO#2]
Hello, I noticed that the newer versions of pix2pix no longer use the --which_direction and --how_many parameters that are called in src/synb0.m here. I was wondering what revision id/commit of pytorch-CycleGAN-and-pix2pix this code is using so I can run those commands as intended.

Any help would be greatly appreciated!

**Comment by hanscol** [comment]
The sha1 of the version used is 6d9e17390a4b2e186bc45427c37f4ff42409bb40 which I believe you can use to checkout the correct older version. However, if you would just like to apply our trained model, a docker is currently available at hansencb/synb0-disco on docker hub.

**Comment by salimansourc** [comment]
Thanks! Also, do you have the "checkpoints" data for your trained model available? Running the pix2pix commands without the checkpoints data throws an error because it can't access "./checkpoints/b0ganRGB-axi_pix2pix/latest_net_G.pth".

**Comment by hanscol** [comment]
These files are too large to commit to github, so I've temporarily put them on my google drive. You should be able to download them here: https://drive.google.com/file/d/1W_gYAWzCluP3pS9l-4eoL1Q7i3uJqixY/view?usp=sharing

**Comment by salimansourc** [comment]
I was able to run the script with the models just fine. Thanks for all your help!
