### ISSUE TITLE
Mask to feed into EDDY 

### ISSUE THREAD

**Issue by SabreA7** [MASILab/Synb0-DISCO#20]
Hi team, 

I have successfully run Synb0 and am preparing to feed the data in EDDY. I was wondering in order to create a brain mask for EDDY, should I be using the Synb0 output for this? if so, which file? 

Thank you for your help,

**Comment by hanscol** [comment]
The current Synb0 output does not include a brain mask. We do run bet to skullstrip the T1 image, but we don't save the mask itself. Anyways you would want a mask in the same space as your diffusion data not the T1. The easiest thing to do would be to use bet to get a mask using your topup corrected b0 image.

**Comment by SabreA7** [comment]
Brilliant, thank you so much for the advice.
