### ISSUE TITLE
Edges of the topup_fieldcoef image have abnormal signal

### ISSUE THREAD

**Issue by treanus** [MASILab/Synb0-DISCO#26]
Hi, 

thanks for making synb0 available.

Recently I have a number of datasets where the edges of the fieldcoef image look strange. The top few rows and the anterior few rows contain wrapped signal. See:

![Screenshot from 2021-09-15 15-49-40](https://user-images.githubusercontent.com/36293632/133447690-bc7ac053-a8e1-483f-9732-0174bee77769.png)

This leads to abnormal signal in the output of eddy. It as as if the signal from the eyes is aliased a few times at the far left of the processed dwi images.

![Screenshot from 2021-09-15 15-56-25](https://user-images.githubusercontent.com/36293632/133447847-7b0439e8-6342-48a3-8c95-dce90411f278.png)

Is this related to the FOV of the T1 and dwi not being equal?

![Screenshot from 2021-09-15 15-47-54](https://user-images.githubusercontent.com/36293632/133448135-36ed97c7-06f2-4ff7-8746-3bae99d05e31.png)

**Comment by iPsych** [comment]
@treanus I am experiencing same issue. I guess that, possibly it's due to wrong acqparams.txt value.
Any advance in this issue?

**Comment by schillkg** [comment]
That is indeed strange. We can do a quick debug to figure out whether it is the synthesis or a topup-related issue. Does the synthesized b0 image look reasonable (b0_u.nii.gz, or the 2nd volume in b0_all.nii.gz) ? It should have the same contrast as the distorted b0, but should look noticeably less distorted (and smoothed just a little bit). If this looks good, it is probably a topup issue - I'm not sure that is wrapped signal? I don't think we expect anything in that area from the posterior of the brain? it just seems like topup isn't well estimating the field near the eyes and is doing something funny with that signal?

**Comment by robbwh** [comment]
potentially related:
https://github.com/MASILab/SynBOLD-DisCo/issues/1

**Comment by iPsych** [comment]
<img width="559" alt="Screen Shot 2023-11-19 at 9 02 24 PM" src="https://github.com/MASILab/Synb0-DISCO/assets/28276515/68a9a09f-a615-4d79-ba78-a3517173d707">
<img width="565" alt="Screen Shot 2023-11-19 at 9 02 44 PM" src="https://github.com/MASILab/Synb0-DISCO/assets/28276515/9ff62fc5-36ad-42c9-8032-ce3f37f11124">
<img width="568" alt="Screen Shot 2023-11-19 at 9 02 29 PM" src="https://github.com/MASILab/Synb0-DISCO/assets/28276515/f0548a26-7bc3-4e90-a3e7-bfa42a55f406">
It seems the possible topup issue. b0_all_topup.nii.gz looks not that problematic, but the result of fsldwipreproc with topup options using below command gives distorted output, especially first and last slides.

`wi_den_unr_preproc.mif -pe_dir AP -rpe_none -eddy_options " --slm=none --data_is_shelled" -fslgrad INPUTS/bvec INPUTS/bval -topup_files OUTPUTs/topup_ `

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
