### ISSUE TITLE
Importance of readout time metric

### ISSUE THREAD

**Issue by ConorOW** [MASILab/Synb0-DISCO#27]
Hey Synb0 team,

Just wanted to ask if you had any advice or thoughts about the importance of the readout time metric that we use for the for the first row of the acqp.txt file?

The FSL folks said in one of their tutorials on TOPUP that in 95% of cases this value isn't really important for that tool, so I had not been paying it much mind when running some data through Synb0. But a colleague has led me to believe I might be making a misstep.

Grateful for any advice.

Conor

**Comment by schillkg** [comment]
Hello,

For our purposes - this value is unimportant. It only needs to be "not 0". The units of the topup field coefficients are linked to the value in the acqparams file, so topup/eddy will know how far to push/pull the image. However, if you want a field in meaningful units (Hz) for subsequent analysis, then this value becomes important.
