### ISSUE TITLE
Synb0 Generation includes Skull

### ISSUE THREAD

**Issue by salimansourc** [MASILab/Synb0-DISCO#3]
Hi, I've recently run into a problem with Synb0 generation which can be seen in the screenshots provided. When comparing the b0 (red/yellow) to the T1 (black/white) it was generated from, it shows that the b0 includes part of the skull as its brain (see top part of skull). 

Have you run into any similar issues like this, and are there any solutions to fixing it?

Transparent Overlay:
![issue_overlay](https://user-images.githubusercontent.com/50180399/60904460-1b884480-a241-11e9-8a12-ba9c2d9f30b4.png)
Synb0:
![issue_synb0](https://user-images.githubusercontent.com/50180399/60903025-a0259380-a23e-11e9-9b17-de00d8c52350.png)
T1:
![issue_t1](https://user-images.githubusercontent.com/50180399/60903026-a0259380-a23e-11e9-9ee7-ee3c2f5b1bd2.png)

**Comment by vuiiscci** [comment]
Can you post your T1 and synthesized b0 somewhere so we can take a look?

**Comment by salimansourc** [comment]
Sorry for the late response, was trying it on more subjects and I've found a solution. Using bias field correction on the T1 before generating the Synb0 produces a much better result.
