### ISSUE TITLE
Transformation from original b0 to synthesized b0

### ISSUE THREAD

**Issue by cnicolasgr** [MASILab/Synb0-DISCO#30]
Hi all,

I am trying to use this tool to correct DWI images that were acquired without reverse phase-encoding scan to feed them into the MRtrix3 pipeline. So I would like to use Synb0-DISCO to get the transform field from the original b0 images to the synthetized one, then use this to register the whole original DWI to an undistorted DWI. Then, I would use this undistorted DWI as an input for the command `dwipreproc` from the MRtrix3 framework.

However I don't see this transform field in the OUTPUTS folder, do you know how I could get it ? I tried to run `applytopup` with the original DWI as input and the generated topup field but it didn't seems to do anything.

Thank you!

**Comment by schillkg** [comment]
In most cases, you will not need to worry about the transforms provided as outputs. The synthesized image, and all topup outputs, will be in the space defined by the original (distorted) b0. For working with MRtrix, I believe you have a few options (as discussed here https://community.mrtrix.org/t/synb0-disco/3954). The easiest solution may simply be to pass the topup output prefix ("topup" in our case) to dwifslpreproc or dwipreproc. It is important to note that topup results (here, topup_fieldcoef.nii.gz) may appear as if they are not in diffusion space, but topup/eddy handle this internally.
