### ISSUE TITLE
Difference in output between 3.0 and previous version

### ISSUE THREAD

**Issue by robbwh** [MASILab/Synb0-DISCO#34]
Hi from a VMAC PhD student, 

I just wanted to point out a difference I noticed between the previous and new docker image:
hansencb/synb0:latest
leonyichencai/synb0-disco:latest

I am using this tool, unconventionally, to correct for distortion in BOLD fMRI images. So no need to troubleshoot for my sake.

New version b0_u.nii.gz:
Darker than expected ventricles (maybe due to spreading out the choroid plexus values)

<img width="1456" alt="Screen Shot 2022-09-13 at 2 56 31 PM" src="https://user-images.githubusercontent.com/39274562/189997099-d16702f5-172e-420f-b86d-eeeb48a54b6c.png">

Older version b0_u.nii.gz doesn't spread out choroid plexus values

<img width="1512" alt="Screen Shot 2022-09-13 at 2 57 41 PM" src="https://user-images.githubusercontent.com/39274562/189997306-0998414b-f3cb-47e4-8456-8d1697fc3061.png">

I used the --stripped command for the new version and input the T1_mask.nii.gz and T1.nii.gz for the old version, which I thought would give similar performance. 

Not sure why this might be, but thought I might as well point it out.

**Comment by leonyichencai** [comment]
Hello! For the old version, was T1.nii.gz already skull stripped? Same for T1_mask.nii.gz? The registration step changed slightly to more accurately account for stripped inputs between hansencb/synb0:latest and leonyichencai/synb0-disco:latest. But also, we're happy to point you to this repo where we have implemented Synb0 for fMRI BOLD (called SynBOLD)! We are still in the validation stages, but would love to have your input: https://github.com/MASILab/SynBOLD-DisCo

**Comment by robbwh** [comment]
Thanks for pointing me to that repo--will check it out shortly!

For the old version: T1.nii.gz was not skull stripped but T1_mask.nii.gz was. 

I'll see what happens using the BOLD version.

**Comment by robbwh** [comment]
Tried out SynBOLD-DisCo and choroid plexus looks good now--there is another slight issue with the first person I tried, but I will make an issue on that github page
