### ISSUE TITLE
Docker Error when Running BBR

### ISSUE THREAD

**Issue by lautzetin** [MASILab/Synb0-DISCO#35]
Hi,

Thank you very much for sharing this program. I'm new to the Synb0 pipeline and ran into this error, where the process kept noticing "ERROR::set_bbr_seg: could not find any boundary points!" when running BBR. I have data from 20 subjects (20 pairs of b0.nii.gz and T1.nii.g), and more than half of them (12/20)
 ran into this error.
 
I ran Synb0 on Ubuntu 14 on vmware, with 4 CPUs, 16GB RAM, 2GB SWAP and 100GB of hard disk to use.

The acqparams.txt as follows:

0 1 0 0.0310798
0 1 0 0.000

I'm attaching what has been printed on the terminal

[error_running_BBR.txt](https://github.com/MASILab/Synb0-DISCO/files/9650354/error_running_BBR.txt)

If you have any idea, please let me know. 

Thank you in advance!

Best,
Zitian

**Comment by Diffusion-MRI** [comment]
Hi @lautzetin - I see you closed this - were you able to solve the issue? I have not seen this before within the singularity image, but have seen it when running epi_reg when the T1 was incorrectly masked. Thank you.

**Comment by lautzetin** [comment]
Hi @Diffusion-MRI 

Thank you for your reply. Indeed, the incorrectly masked T1.nii.gz seems to be the reaseon of this error. I accidentally performed Synb0 on T1 which was converted from FreeSurfer result files (*.mgz). After using the raw T1 scan, I could now get all my data done.

Thank you for this great tool. It really helps a lot!

Cheers,
Zitian
