### ISSUE TITLE
Error while running the first command on Docker "docker: failed to register layer"

### ISSUE THREAD

**Issue by Mtay316** [MASILab/Synb0-DISCO#36]
Hi , 
First of all I wanted to say thank you for making this amazing method that can solve lots of distortion correction problems on dataset without reverse gradient. Your work is so precious. 

I tried to run your method on my data and what I did is to run the following command:

sudo docker run --rm \
-v $(pwd)/INPUTS/:/INPUTS/ \
-v $(pwd)/OUTPUTS:/OUTPUTS/ \
-v /usr/local/freesurfer:/extra/freesurfer/license.txt \
--user $(id -u):$(id -g) \
leonyichencai/synb0-disco:v3.0
Password:
Unable to find image 'leonyichencai/synb0-disco:v3.0' locally
v3.0: Pulling from leonyichencai/synb0-disco

As you mentioned in your instruction, as a Mac user I opened my Docker and in the setting I increased the Memory to 40 GB and CPUs to 8 , Swap is 1 GB and Disk Image size is 59.6 GB. 

After running the command , I can see all of the downloading goes complete, apart from the biggest one with 12.38 GB. I can see it goes up to 10 GB and then it drops out and showing this error: 

docker: failed to register layer: Error processing tar file(exit status 1): write /extra/fsl/bin/fdt_matrix_merge: no space left on device.
See 'docker run --help'.

Could you please help me how to sort out this issue?

Big thanks,
Maryam

**Comment by Diffusion-MRI** [comment]
Could you copy the full output or error log? That will help us debug where the error occurs.

Thank you.

**Comment by Mtay316** [comment]
This is everything : 

Unable to find image 'leonyichencai/synb0-disco:v3.0' locally
v3.0: Pulling from leonyichencai/synb0-disco
6abc03819f3e: Pull complete 
05731e63f211: Pull complete 
0bd67c50d6be: Pull complete 
af74ea47daf5: Pull complete 
1183f58ddb5d: Extracting [==================================================>]  12.38GB/12.38GB
bffc45fdfb6e: Download complete 
76e5d712b7df: Download complete 
a8616262ab23: Download complete 
c02c7de5bd7b: Download complete 
96ae328f242e: Download complete 
59c27ab8fec6: Download complete 
727a3d6a1614: Download complete 
224d00df44f6: Download complete 
f8395e755e56: Download complete 
ad0f643c8349: Download complete 
d6d717c50894: Download complete 
9332719043ff: Download complete 
f8b462257835: Download complete 
docker: failed to register layer: Error processing tar file(exit status 1): write /extra/fsl/bin/fdt_matrix_merge: no space left on device.
See 'docker run --help'.

**Comment by Diffusion-MRI** [comment]
This is an error downloading the image. It seems as if you have run out of space on your hard drive? It may be worth downloading on a disk space that you know contains plenty of space (10-12Gb).

**Comment by Mtay316** [comment]
Could you please tell me how to do that? I am not that familiar with Docker. My Hard drive has 2 TB space and still 0.5 TB space left there. I don't know which part of the command to change to download it on a disk space

**Comment by Diffusion-MRI** [comment]
That should be plenty of space. I would try the pulling the docker again (which is the first thing done when you do 'docker run'). It only needs to download once, then all other 'docker run' calls will be much more quick because it will not need to redownload the container.

**Comment by Mtay316** [comment]
I tried again, and this time I logged in the Docker page and found "leonyichencai/synb0-disco" and pulled the docker command from there "docker pull leonyichencai/synb0-disco"

After running this command , I got this error :

Using default tag: latest
latest: Pulling from leonyichencai/synb0-disco
6abc03819f3e: Pull complete 
05731e63f211: Pull complete 
0bd67c50d6be: Pull complete 
af74ea47daf5: Pull complete 
1183f58ddb5d: Extracting [==================================================>]  12.38GB/12.38GB
bffc45fdfb6e: Download complete 
76e5d712b7df: Download complete 
a8616262ab23: Download complete 
c02c7de5bd7b: Download complete 
96ae328f242e: Download complete 
59c27ab8fec6: Download complete 
727a3d6a1614: Download complete 
224d00df44f6: Download complete 
f8395e755e56: Download complete 
ad0f643c8349: Download complete 
d6d717c50894: Download complete 
9332719043ff: Download complete 
f8b462257835: Download complete 
failed to register layer: Error processing tar file(exit status 1): write /extra/fsl/bin/fdt_matrix_merge: no space left on device

Seems like downloading the image is not a problem this time but space is still an issue. What do I need to add to the command to define the space on my hard drive ?

**Comment by Mtay316** [comment]
In order to check how much space can be reclaimed due to unused images, I ran this command: 

docker system df

And what I get was:

TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          3         2         24.74GB   11.23GB (45%)
Containers      4         0         122kB     122kB (100%)
Local Volumes   0         0         0B        0B
Build Cache     36        0         6.237GB   6.237GB


And because RECLAIMABLE amount was greater than zero then I ran command:

docker system prune -a

and it cleaned up all the unused space. 

Now I am running "docker pull leonyichencai/synb0-disco " again. I hope it work this time

**Comment by Mtay316** [comment]
Fortunately It worked and space problem is solved. Thanks

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
