### ISSUE TITLE
[Question] Acqparams in case of multiple b0s

### ISSUE THREAD

**Issue by ajschadler12** [MASILab/Synb0-DISCO#37]
My apologies for the basic question:
In the case of multiple concatenated b0 images, should the acqparams.txt contain _n+1_ rows, _n_ being the number of b0 volumes?

**Comment by Vince-LD** [comment]
Hello,
What I do is average the b0s in a mean b0 volume and use it for synb0 and the topup. I don't know if it's the best thing to do but it gives me very good results.

**Comment by Diffusion-MRI** [comment]
Yes - Vince-LD's solution works well. You could alternatively give it just the first (or any) b0 image. Currently the pipeline does not accept multiple b0 images, but we hope to have this in a future iteration so that motion between volumes can be captured.

**Comment by Vince-LD** [comment]
@Diffusion-MRI,
I thought about this at some point. Do you think adding a simple registration (like flirt with 6 dofs) between all 3D volumes in a 4D b=0 volume could be beneficial?
cheers

**Comment by Vince-LD** [comment]
Thanks for the explanation, but does that mean that there would be one synthetic undistorted b=0 generated for each original b=0?

**Comment by schillkg** [comment]
To clarify - we have not implemented this yet. The idea above is just what would be an ideal situation (and most close to the way topup + eddy currently work) - where topup not only estimates the field but has an initial guess of movement between the b=0 volumes. Our pipeline just accepts a single volume (3D image) for b=0!
