### ISSUE TITLE
Problems installing Synb0 with undockerized and dockerized singularity instructions

### ISSUE THREAD

**Issue by alestella** [MASILab/Synb0-DISCO#41]
Good morning,
I am trying to use Synb0-DISCO in a Ubuntu 20.04 operating system.
I have two distinct problems, one with the undockerized and one with the dockerized singularity modality.

(UNSOLVED) AS per the undockerized instructions, I have successfully run the program (after modifying the paths so that the pipeline.sh pointed at the FSL, Freesurfer, ANTs and Pytorch). However, when running c3d_affine_tool, the function keeps looking for the library libITKIOGDCM-5.2.so.1, whereas in the /usr/local/fsl/...fslpython/lib folder there is only libITKIOGDCM-5.1.so.1! I cannot find the other library, even If I wanted to download it separately.

(SOLVED) As per the dockerized singularity modality, I am having problem because, although my /tmp folder has a capacity of over 200 GB, towards the end of the pulling (singularity pull docker://leonyichencai/synb0-disco:v3.0), it says 'FATAL: ...no space left on device'.
Do you have any idea on how to go on from here?

Any help is very much appreciated, thank you!

**Comment by alestella** [comment]
![image](https://user-images.githubusercontent.com/31692482/212302312-06b83a13-1b32-45f2-9eaa-5baa6e54932a.png)

**Comment by schillkg** [comment]
That is very strange that it is taking up so much space on download. Could you try downloading the container to any other machine then copying? I believe the container is only ~12Gb. Are you somehow pulling the image for each time you call the container?

**Comment by alestella** [comment]
Yes, I have actually repeated the instruction with 'pulling' several times,
but I can assure that the 'Fatal' error popped up since the very first
time. I haven't tried pulling the docker on a different machine though. I
have Windows 10 on my laptop, while the machine I am trying to install
Synb0-DISCO has an Ubuntu 20.04 system.

**Comment by alestella** [comment]
Thanks so much for your reply!

**Comment by alestella** [comment]
Good morning!
I have deleted the previous docker images, and started from fresh.
However, I still get a 'no space left on device' error:
![image](https://user-images.githubusercontent.com/31692482/212900657-1465e7dc-9029-4a72-b008-370a47823ca6.png)

**Comment by alestella** [comment]
Update: I changed strategy completely, and installed a Docker Desktop to run it on Windows 10. 
I had to change slightly the instructions, and to let the contained run in the folder $(pwd) where my inputs were. 
I post here the instructions that worked for me:
docker run -v "$(pwd)/INPUTS/:/INPUTS" -v $(pwd)/OUTPUTS/:/OUTPUTS" leonyichencai/synb0-disco:v3.0

**Comment by alestella** [comment]
Update: I am almost done, meaning that the program does what it is supposed to do. However, at a certain point, when it performs the 'guessings-predictions', an error in the pipeline.sh script pops up, and therefore it doesn't save the b0_u_*_FOLD outputs:
![image](https://user-images.githubusercontent.com/31692482/213136487-cc31f90d-70a9-4273-9bdc-e3f8302e5520.png)
