### ISSUE TITLE
Inquiry about b-values and b0 non-diffusion-weighted image

### ISSUE THREAD

**Issue by nqueder** [MASILab/Synb0-DISCO#42]
Hi, 

I have a few questions regarding your pipeline. 

1. In your README.md file, you mentioned that the input directory should have a b0.nii.gz image. What's the best way you recommend to acquire this b0 non-diffusion-weighted image from the diffusion-weighted image? would fslsplit be good to use here as a preprocessing step? or do you recommend a different tool?

2. The dataset I am working with has b = 5 as the lowest b value rather than a b = 0, would you anticipate this to change the outcome of the Synb0-DISCO pipeline?

Thank you!

**Comment by schillkg** [comment]
Hi nqueder,

1. There are many ways to do this - you could use fslsplit or fslroi from the fsl suite, or functions from the mtrix suite (dwiextract, or similar) to pull out any single b=0 image. It is important that is is just a single 3d volume (and not all b=0 images that are acquired). I imagine most software toolboxes have some function to pull out any desired b=0 image.
2. That is perfectly fine. You can never get a perfect b=0 image, and b=5 is the same for all intents and purposes. 

Kurt
