### ISSUE TITLE
python requirements

### ISSUE THREAD

**Issue by rcruces** [MASILab/Synb0-DISCO#43]
Could you please provide or point me to the python package versions to build a local environment?

**Comment by dr-ir-joost** [comment]
Hi, 

I created a conda enviroment using the following packages (I have a nvidia GPU with CUDA version 11.8):
```
conda create -p ~/SynB0-DISCO python=3.6
conda activate ~/SynB0-DISCO
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 <-- change this line if you have different GPU/CUDA version
pip3 install Pillow six nibabel scipy numpy==1.19
```

Afterwards, I cloned the Synb0-DISCO repo into the conda enviroment and adapted the /src/pipeline.sh and /data-processing/prepare_input.sh files such that my bin folders of FSL, FreeSurfer, ANTs are found. Note that you will also need the c3d_affine_tool, which is not provided by any of these other tools.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
