### ISSUE TITLE
Questions on acqparams

### ISSUE THREAD

**Issue by lyhoo23618-csu** [MASILab/Synb0-DISCO#44]
Dear experts,

 I am wonderring how to set the acqparams file. In my case, my phase encoding direction is "j-", so I set my acqparams.txt as 
“0 -1 0 0.043
 0 -1 0 0”

Can you help me check this is correct or not? I want to know whether the parameters of the synthesized, undistorted, b0 should keep consistent with my orginal real b0 volume.

Thanks a lot.

Kind regards,
Hao Li, 
MD, PhD candidate,
Radboud UMC, Nijmegen, the Netherlands

**Comment by njhunsak** [comment]
Great question. I would love to know the answer as well. Does the synthesized, undistorted b0 image match the PED of the original b0, should it be set with opposing PED, or is it always set to `0, 1, 0, 0`?

**Comment by schillkg** [comment]
Hi all - sorry for the delayed response. The answer is that it doesn't matter, as long as the total readout time (the 4th index) is set to 0! The acqparams in the documentation just happens to be how we tested and validated the algorithm, but TOPUP is smart enough that you can actually do 1 0 0 0, -1 0 0 0, 0 1 0 0, 0 -1 0 0, 0 0 1 0, etc., these in theory will all lead to the same distortion (i.e. no distortion).
