### ISSUE TITLE
Fails to run inferences (predictions) for five folds 

### ISSUE THREAD

**Issue by kyokodayo** [MASILab/Synb0-DISCO#46]
I am a newbie and would appreciate any insights.
I managed to install Docker and start running the command below.

sudo docker run --rm \
-v $(pwd)/INPUTS/:/INPUTS/ \
-v $(pwd)/OUTPUTS:/OUTPUTS/ \
-v $(pwd)/license.txt:/extra/freesurfer/license.txt \
--user $(id -u):$(id -g) \

It runs up until the inferences for five folds. Then I get the error performing inferences as below. The error is the same for all FOLDs.

Performing inference on FOLD: 1
/extra/pipeline.sh: line 42:  1610 Killed                  python3.6 /extra/inference.py /OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz /OUTPUTS/b0_d_lin_atlas_2_5.nii.gz /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_"$i".nii.gz /extra/dual_channel_unet/num_fold_"$i"_total_folds_"$NUM_FOLDS"_seed_1_num_epochs_100_lr_0.0001_betas_\(0.9\,\ 0.999\)_weight_decay_1e-05_num_epoch_*.pth

I don't know if I'm missing something obvious.. Please help.
Thank you!!

**Comment by schillkg** [comment]
This is just a simple memory issue. Increase your RAM (we recommend >12Gb, but some systems require >16) and you will successfully run the pipeline.

**Comment by kyokodayo** [comment]
It's running!
Thank you so much!!
