### ISSUE TITLE
Synb0-DISCO failed, error with ANTS registration?

### ISSUE THREAD

**Issue by george-gifford** [MASILab/Synb0-DISCO#48]
Hi there,

Running synb0-DISCO is failing for me. I'm running several subjects by sending the jobs to a slurm server. 

It looks like ANTS registration is failing with the error:

ERROR:  The number of shrink factors does not match the number of levels.
Shrink Factors: 4
Number Of Levels: 1

Could it be related to this issue?
https://github.com/ANTsX/ANTs/issues/712

I've attached the output:
[902071_1.txt](https://github.com/MASILab/Synb0-DISCO/files/11443490/902071_1.txt)

Big thanks in advance!

**Comment by schillkg** [comment]
This is certainly a unique error! Is it reproducible? I'm unsure it is related to that issue - seems that is more a file path + file name issue, where ours is hard-coded within the container. If data is easily shared, we can try reproducing the error on our end.

**Comment by george-gifford** [comment]
Thanks for getting back to me!

I've run on the same data on my local computer. I have a different error but the same outcome, please see the attached output.

Any recommendations for what to try?

[output_synb0_disco.txt](https://github.com/MASILab/Synb0-DISCO/files/11544232/output_synb0_disco.txt)

**Comment by george-gifford** [comment]
Hi just to say this issue is resolved. It ran fine if we moved into the directory containing the INPUT and OUTPUT folders before calling synb0-DISCO. Thanks for your help!
