### ISSUE TITLE
Problems encounter on Docker

### ISSUE THREAD

**Issue by oscarwongwh** [MASILab/Synb0-DISCO#5]
Hi there, 
I have installed the app on docker and was trying to run it on a subject. However I got stuck repeated on this place where the ANTs script would not work
"/extra/ANTS/ANTs/Scripts/antsRegistrationSyNQuick.sh: line 606:  1218 Killed                  $COMMAND"
Can anyone give me some advice on how to solve this problem?
Many thanks

**Comment by baxpr** [comment]
@oscarwongwh I'm not the expert on this particular container, but when I've seen similar errors in the past it's been because I needed to expand some memory limits given to Docker.

**Comment by ahilderley** [comment]
@oscarwongwh were you able to resolve this? I'm having the same issue.

**Comment by schillkg** [comment]
This is almost certainly a memory issue. Especially for Mac users, Docker defaults allows only 2gb of RAM and 2 cores - we suggest giving Docker access to >8Gb of RAM.
