### ISSUE TITLE
Query on running EDDY after synb0

### ISSUE THREAD

**Issue by george-gifford** [MASILab/Synb0-DISCO#50]
Hi there,

When you run eddy after synb0, e.g.

eddy --imain=path/to/diffusiondata.nii.gz --mask=path/to/brainmask.nii.gz \
--acqp=path/to/acqparams.txt --index=path/to/index.txt \
--bvecs=path/to/bvecs.txt --bvals=path/to/bvals.txt 
--topup=path/to/OUTPUTS/topup --out=eddy_unwarped_images

Is --imain=path/to/diffusiondata.nii.gz the orginal distorted file and --mask=path/to/brainmask.nii.gz a brain mask that is computed on the undistorted b0?

Or should --imain=path/to/diffusiondata.nii.gz be undisorted?

Many thanks for any advice!
George

**Comment by schillkg** [comment]
Hi George - yes, it should point to the original, raw diffusion data, and the brain mask is indeed a mask. The mask doesn't need to be perfect at this stage - FSL recommends running BET command on the topup output (topup_iout.nii.gz, or similar) (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#A--mask).
