### ISSUE TITLE
Missing total readout time for Philips scanners

### ISSUE THREAD

**Issue by george-gifford** [MASILab/Synb0-DISCO#52]
Hi there,

We have some scans that were performed on a Philips scanner, where we don't have the total readout time, so can't enter the correct value in acqparams.txt.

Am I right that this would preclude synb0-disco as the readout times between the b0 and T1 are different?

Many thanks,
George

**Comment by george-gifford** [comment]
Apologies, the T1 is mentioned in error in the above message. The question is just whether there is a way to use synb0-disco when the information needed for the total readout time is missing, as it is for some Phillips scans.

**Comment by george-gifford** [comment]
That's great news ok! I'll default to 0.05.

Many thanks for dealing with this and other queries!

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
