### ISSUE TITLE
Does pipeline.sh use GPU?

### ISSUE THREAD

**Issue by tashrifbillah** [MASILab/Synb0-DISCO#53]
```
epi_reg distorted b0 to T1
epi_reg --epi=/INPUTS/b0.nii.gz --t1=/INPUTS/T1.nii.gz --t1brain=/tmp/tmp.z3zFpgMgdl/T1_mask.nii.gz --out=/tmp/tmp.z3zFpgMgdl/epi_reg_d
Running FAST segmentation
FLIRT pre-alignment
Running BBR
```

Shouldn't this step use GPU? `nvidia-smi` command does not print an associated GPU process at the time of running.

**Comment by toomanycats** [comment]
I'm not a developer or expert with this program. However, I'd say no. 
Those are just FSL programs. They use CPUs and can use multiple threads. 

AFAIK, nothing in the pipeline uses GPU. The model is already built and so `inference` is just a forward run through the model and uses CPU. IN fact, I know that the `torch` library in the container version, was not compiled for GPUs.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
