### ISSUE TITLE
c3d_affine_tool: command not found

### ISSUE THREAD

**Issue by dr-ir-joost** [MASILab/Synb0-DISCO#54]
I am using the non-containerized version of Synb0-DISCO, which according to the instructions only needs FSL, FreeSurfer, ANTs and Python. After setting the correct paths to the bin-folders of FSL, FreeSurfer, ANTs and Python/Pytorch and adapting /src/pipeline.sh and  /data_processing/prepare_input.sh accordingly, there are a few issues which I think are noteworthy:
1) it seems that the script prepare_input.sh requires c3d_affine_tool. This tool is not included in FSL, FreeSurfer, ANTs or Python. Please update the instructions that c3d_affine_tool is also required. 
2) pipeline.sh has a reference to the path /dual_channel_unet, but this does not exist. This needs to be changed to /src/train_lin (or please provide the dual_channel_unet folder).
3) the inference.py script gives an error when it is being executed in an environment in which the CPU version of Pytorch is installed. After creating a conda environment with appropriate drivers and the Pytorch version that runs on GPU, this is error is solved.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
