### ISSUE TITLE
Info requested from developers for DIPY implementation

### ISSUE THREAD

**Issue by smeisler** [MASILab/Synb0-DISCO#57]
Hello,

I know this is not a bug, but I would like to ask if any developer could kindly weigh in on some considerations for synb0-DISCO implementation in DIPY on this thread here: https://github.com/dipy/dipy/discussions/2811#discussioncomment-7854876.

Thank you,
Steven

**Comment by smeisler** [comment]
Same discussion is happening here: https://github.com/dipy/dipy/discussions/2853

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
