### ISSUE TITLE
Issues with susceptibility distortion correction in brainstem

### ISSUE THREAD

**Issue by halmgren** [MASILab/Synb0-DISCO#62]
Hi there,

Thank you very much for creating and sharing this amazing tool. 

I am having issues with susceptibility distortion corrections in the brainstem. I generated the synthetic b0-file (see below), which follows the anatomy quite well. However, when I use FSLtopup with synb0 the brainstem somehow gets squeezed, which affects tractography eventually (see below). My brainmask covers the brainstem quite well, so that shouldn’t be the issue.

I was wondering whether you have encountered anything similar before.

Best,

Hannes

------------------------------------

**Synthetic b0:**
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/eb439fc9-eea8-48eb-aee8-f0d3ec0674a6)

**T1w image:**
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/c5fa976d-7a03-45da-92f5-3a986cbd8fbf)

**Raw b0:**
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/31655e05-ad9c-4d01-b05e-56d570cd3bc5)

**Corrected b0:**
# screenshot 1
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/a404eeae-628e-40bf-92b6-930adeea8d69)

# screenshot 2
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/e2f0f4b0-be8f-41d9-9584-3b22b090f4e8)

**Corrected b0 overlaid on T1w image:**
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/0b7fe795-a032-47a3-a472-41e9c9001453)

**Tractography:**
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/16a8cb8f-1e33-4ecc-b23a-8334c4d3d936)

**Comment by schillkg** [comment]
Hi Hannes - you are right, I don't quite like what is happening in the brainstem. We generally go through a few steps to debug.

First - it is hard to tell on the screen grab, but we ask 'is the synthetic b0 reasonable'? I like to look at this in two ways. First, I look at b0_all and flip between the first and second volumes. The first is the distorted (acquired b0), the second is the synthesized. Hopefully, the synthesized is less-distorted, and is correctly 'stretched' in in the brainstem region. Second, I like to compare the synthetic b0 to the T1 and ask whether it better matches than the original distorted data. It appears based on the screen grab that it does, but I can't quite confirm.

Second - does the topup correction using the distorted+synthesized image work? I usually look at b0_all_topup and flip between the first and second volumes. These should 'ideally' be the same geometry, or similar. Can you confirm that this is indeed the case?

If not, we can slowly debug step by step. I would maybe try this without the brain mask (as that is the default settings and how this was trained), then try it with the brain mask if that fails.

Let me know about #1 and #2 above.

Thank you - Kurt

**Comment by halmgren** [comment]
Hi Kurt,

Thanks for your prompt reply. 

The synthesized b0-image does coregister well with the T1w image, however, the boundaries of the brainstem are much less well-defined compared to the raw b0 (see below for screenshots). 

The problem indeed occurs when I use topup with those images. The corrected b0 (first image of b0_all_topup) looks very blurry (see below), while the synthesized b0 still looks fine. I didn't use a brainmask for this step (it was used for eddy-current correction later), I stuck to the default.

Best,

Hannes

-------
synthesized B0:
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/f51b0956-b705-4838-8ee2-9baf3acd0e2c)

raw b0: 
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/0bf27aa1-b919-4126-814b-62fbe423c4cc)

corrected b0:
![image](https://github.com/MASILab/Synb0-DISCO/assets/14106687/7bbd7be9-a61d-40c5-bfb2-f67d07139f02)

**Comment by halmgren** [comment]
Hi, Thanks for your response. I already ran topup separately from the synb0-container using the b02b0.cnf configuration file, but that didn't change much. I will play around with the topup-configurations and see whether that helps.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
