### ISSUE TITLE
Topup

### ISSUE THREAD

**Issue by ash692i** [MASILab/Synb0-DISCO#65]
Hi . After using Synb0, eddy was set up. But it’s unable to read topup outputs mentioned in the OUTPUTS directory. Do you know why this is happening?  

As an alternative I tried to skip topup and decided to run it after running Synb0. So specified --notopup at the end of the Synb0 command (path to synb0.simg --notopup). However it says command not found and runs topup. Where exactly --notopup needs to be specified. And why is eddy unable to read topup output generated?

**Comment by schillkg** [comment]
Can you post the command you are running, and the error that eddy gives?

**Comment by ash692i** [comment]
singularity run -e \
-B INPUTS/:/INPUTS \
-B OUTPUTS/:/OUTPUTS \
-B <path to license.txt>:/extra/freesurfer/license.txt \
path to synb0.simg
--notopup

This still produces topup output.

•	topup_movpar.txt
•	b0_all_topup.nii.gz
•	b0_all.topup_log
•	topup_fieldcoef.nii.gz


eddy --imain=dwi.nii.gz --mask=brain_mask --acqp=acqparams.txt --index=index.txt --bvecs=dwi.bvec --bvals=dwi.bval --topup=OUTPUTS/topup --out=eddy_unwarped_images 

TopupFileIO::TopupFileReader::TopupFileReader: Unable to read file OUTPUTS/topup

Terminating program

**Comment by ash692i** [comment]
singularity run -e \
-B INPUTS/:/INPUTS \
-B OUTPUTS/:/OUTPUTS \
-B <path to license.txt>:/extra/freesurfer/license.txt \
path to synb0.simg
--notopup

This still produces topup output.

•	topup_movpar.txt
•	b0_all_topup.nii.gz
•	b0_all.topup_log
•	topup_fieldcoef.nii.gz


eddy --imain=dwi.nii.gz --mask=brain_mask --acqp=acqparams.txt --index=index.txt --bvecs=dwi.bvec --bvals=dwi.bval --topup=OUTPUTS/topup --out=eddy_unwarped_images 

Error:
TopupFileIO::TopupFileReader::TopupFileReader: Unable to read file OUTPUTS/topup

Terminating program

**Comment by schillkg** [comment]
It is a bit hard to debug, but I'm surprised the singularity runs with spaces in "path to synb0.simg". Does the topup output look reasonable?

Eddy is failing because it cannot find topup_movpar.txt and topup_fieldcoef.nii.gz. Are you sure you are pointing towards the correct locations?

Thank you,
Kurt

**Comment by ash692i** [comment]
The actual path to singularity does not have space. Here I thought to add the path name as a text. The --notopup command be specified at the end of the command? Specifying it at the end generates the warning --notopup command not found.

Also, the topup outputs are generated in the OUTPUT folder. I tried absolute and relative path. Still it’s unable to read the topup output files generated. 

That’s why I thought of running topup externally. But using --notopup at the end, still generates topup files.

**Comment by ash692i** [comment]
The actual path to singularity does not have space. Here I thought to add the path name as a text. The --notopup command should be specified at the end of the command? Specifying it at the end generates the warning --notopup command not found.

Also, the topup outputs are generated in the OUTPUT folder. I tried absolute and relative path. Still it’s unable to read the topup output files generated. 

That’s why I thought of running topup externally. But using --notopup at the end, still generates topup files.

**Comment by schillkg** [comment]
You can run topup externally regardless of whether or not --notopup was on/off. So the fact that you cannot run topup/eddy separately seems to suggest it is an issue with getting topup/eddy to run.

Do the OUTPUTS/topup* seem reasonable? If so, the synb0 is working and the issue is getting eddy to run.

Does b0_all look reasonable? If so, you can you just run topup on the b0_all volume directly.
