### ISSUE TITLE
Missing b0_all.nii.gz with --notopup flag

### ISSUE THREAD

**Issue by ivonnecruz** [MASILab/Synb0-DISCO#66]
Hi! I’m working with a dataset that doesn't use reverse encoding (60 dir, b = 1000, PE-dir = j-). Recently, I was exploring Synb0-DISCO to obtain `b0_all.nii.gz` and use it in a customized version of eddy/topup. However, when I use the `--notopup` flag, I don’t find the `b0_all.nii.gz` file in the outputs folder.

```
sudo docker run --rm \
-v $(pwd)/INPUTS/:/INPUTS/ \
-v $(pwd)/OUTPUTS:/OUTPUTS/ \
-v /usr/local/freesurfer/7.4.1/license.txt:/extra/freesurfer/license.txt \
--user $(id -u):$(id -g) \
leonyichencai/synb0-disco:v3.0 \
--notopup
```

![SYNB0_outputs](https://github.com/MASILab/Synb0-DISCO/assets/142020067/03b424ce-baa9-4191-8679-3db7a26d7b42)

I’m wondering if I can obtain the equivalent of `b0_all.nii.gz` by concatenating `b0_d_smooth.nii.gz` and `b0_u.nii.gz`. I tried this command: `fslmerge -t b0_all.nii.gz b0_d_smooth.nii.gz b0_u.nii.gz`

It's important to mention that I am working with Windows Subsystem for Linux (WSL 2, Windows 10, Ubuntu 22).

Any suggestion is welcome. Thanks!

**Comment by schillkg** [comment]
Thank you for opening this issue, we should mention this in our README. You can indeed run:

fslmerge -t /OUTPUTS/b0_all.nii.gz /OUTPUTS/b0_d_smooth.nii.gz /OUTPUTS/b0_u.nii.gz

This is how we do it internally within the container, and should results in an image that is ready for topup-like processing.
