### ISSUE TITLE
Could not open matrix file /tmp/tmp.CAniyjLkgw/epi_reg_d.mat

### ISSUE THREAD

**Issue by mmelmendili** [MASILab/Synb0-DISCO#67]
Hi,
I got an error related to epi_regt:

Copying user provided T1 Mask
-------
epi_reg distorted b0 to T1
epi_reg --epi=/INPUTS/b0.nii.gz --t1=/INPUTS/T1.nii.gz --t1brain=/tmp/tmp.CAniyjLkgw/T1_mask.nii.gz --out=/tmp/tmp.CAniyjLkgw/epi_reg_d
Running FAST segmentation
FLIRT pre-alignment
Running BBR
Image Exception : #75 :: 3D only method called by higher-dimensional volume.
3D only method called by higher-dimensional volume.
Could not open matrix file /tmp/tmp.CAniyjLkgw/epi_reg_d.mat
/extra/fsl/bin/epi_reg: line 399:   958 Segmentation fault      (core dumped) $FSLDIR/bin/applywarp -i ${vepi} -r ${vrefhead} -o ${vout} --premat=${vout}.mat --interp=spline

Whether I provide a T1 mask or not, I get the same error.
I am using Doker container.
Could you please help me with this issue ?

Thank you very much,
MM

**Comment by schillkg** [comment]
Can you verify that both the b0.nii.gz and T1.nii.gz are 3D volumes only? A common mistake is giving all b=0 images as inputs as a 4D volume.

**Comment by schillkg** [comment]
We are marking this as complete. Allowing multiple b=0 images is a feature to include in future updates.
