### ISSUE TITLE
singularity: Image Exception : #75 :: 3D only method called by higher-dimensional volume.

### ISSUE THREAD

**Issue by renelabounek** [MASILab/Synb0-DISCO#69]
Dear Synb0-DISCO developers,

I have build a singularity package but am  not able to sucessfully execute the distortion correction. The commands that I execute are bellow, same as summary of my INPUTS and begginiing of the error message. b0_d_smooth.nii.gz is the last generated image file. Please, any idea what I can do wrong?

Best regards,
Rene 

`
cd /home/raid4/data/dmri-synb0-test/sub-0050/ses-01
`

`
singularity run -e -B /var,/run -B /home/raid1,/home/raid2,/home/raid3,/home/raid4,/home/raid5 -B /home/raid6,/home/raid7 -B /home/raid4/data/dmri-synb0-test/sub-0050/ses-01/:/INPUTS -B  /home/raid4/data/dmri-synb0-test/sub-0050/ses-01/:/OUTPUTS -B ~/lib/freesurfer7/license.txt:/extra/freesurfer/license.txt /home/raid5/lib/Synb0-DISCO/synb0-disco_v3.1.sif --stripped > symb0-disco.stdout
`

**INPUT files** in the dataset folder are:

*b0.nii.gz* (4D-file of 4 PA b0 volumes)
*T1.nii.gz* (3D skull stripped mprage)
*acqparams.txt* (5 rows text file below)

0 1 0 0.0632499
0 1 0 0.0632499
0 1 0 0.0632499
0 1 0 0.0632499
0 1 0 0.0000000

Everytime, the error messages starts as follows. I assume that the higher-dimensional volume is the beginning of the issue, but lack to identify it more.

Saving result to '/tmp/tmp.RKPwSBxQCB/tmp.mri_nu_correct.mni.110457/nu2.mnc' (type = MINC )                       [ ok ]
**Image Exception : #75 :: 3D only method called by higher-dimensional volume.**
**3D only method called by higher-dimensional volume.**
Could not open matrix file /tmp/tmp.2IuLM5Gt0J/epi_reg_d.mat
/extra/fsl/bin/epi_reg: line 399: 121089 Segmentation fault      (core dumped) $FSLDIR/bin/applywarp -i ${vepi} -r ${vrefhead} -o ${vout} --premat=${vout}.mat --interp=spline
terminate called after throwing an instance of 'char const*'
/extra/prepare_input.sh: line 69: 121319 Aborted                 (core dumped) c3d_affine_tool -ref /INPUTS/T1.nii.gz -src /INPUTS/b0.nii.gz /tmp/tmp.2IuLM5Gt0J/epi_reg_d.mat -fsl2ras -oitk /tmp/tmp.2IuLM5Gt0J/epi_reg_d_ANTS.txt
Transform file does not exist: /tmp/tmp.2IuLM5Gt0J/epi_reg_d_ANTS.txt
Transform file does not exist: /tmp/tmp.2IuLM5Gt0J/epi_reg_d_ANTS.txt
cp: cannot stat '/tmp/tmp.2IuLM5Gt0J/epi_reg_d.mat': No such file or directory
cp: cannot stat '/tmp/tmp.2IuLM5Gt0J/epi_reg_d_ANTS.txt': No such file or directory
cp: cannot stat '/tmp/tmp.2IuLM5Gt0J/b0_d_lin_atlas_2_5.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.2IuLM5Gt0J/b0_d_nonlin_atlas_2_5.nii.gz': No such file or directory
Traceback (most recent call last):
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/OUTPUTS/b0_d_lin_atlas_2_5.nii.gz'

**Comment by renelabounek** [comment]
I see I have the same problem as in #67. If the library can not work with multiple b0 scans, why is then in the README b0 input defined in plural? Can I utilize multiple b0 scans to enhance SNR?

>  b0.nii.gz: the non-diffusion weighted image(s)

**Comment by schillkg** [comment]
Currently this accepts only a single 3D volume as b0.nii.gz. We advocate using all b=0's within topup and eddy itself, but for the synthesis we want only a single 3D volume - whether it is the first, the best, or the average. Most of the SNR (or at least the CNR and geometry) will come from the T1 image. We will adapt the README to remove the suggestion that multiple b=0 are acceptable.

**Comment by schillkg** [comment]
We are marking this as complete. Allowing multiple b=0 images is a feature to include in future updates.
