### ISSUE TITLE
Problems with singularity

### ISSUE THREAD

**Issue by wkwill** [MASILab/Synb0-DISCO#7]
Hi, 

I am trying to run this using singularity but I encounter an error downloading the latest build. 

This is the error produced when running the following command: 

singularity run -e \
-B INPUTS/:/INPUTS \
-B OUTPUTS/:/OUTPUTS \
-B $(pwd)/license.txt:/extra/freesurfer/license.txt \
shub://hanscol/synb0
FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub

I had a look on singularity hub and the latest status for this appears to show an error. 

Cheers, 

Will

**Comment by baxpr** [comment]
Hi Will - first things first, this no reflection on you but please do not run containers directly from shub - see here, especially the "Get" limit:
https://singularityhub.github.io/singularityhub-docs/docs/regulatory/limits
Instead, pull the container (`singularity pull ...`) and run it locally.

@schillkg @hanscol - the reflection is on you ;) please read the above and update the synb0 README accordingly. The problem here might even be that your shub limits have been exceeded due to too many pulls from people following this procedure.

@hanscol please check your shub account and see if things look ok and there is a container available under `synb0`.

By that time maybe the issue will be figured out and we can get Will going.

**Comment by baxpr** [comment]
@wkwill Meanwhile, if you like you can try grabbing the Singularity file here and build it yourself locally:

`singularity build Singularity`

Or whatever the right command is. It is a very simple recipe, just pulls the docker container.

**Comment by baxpr** [comment]
@vsoch reminds me you can also pull directly from dockerhub:

`singularity pull docker://hansencb/synb0`

**Comment by yjp16GH** [comment]
Hi All, 

I've had a go at running the above command (singularity pull docker://hansencb/synb0) and have not been successful; P.S. it's also my first time using this. I receive the following error was hoping if anyone could help:  

FATAL: While making image from oci registry: while building ISF from layers: unable to create new build: while searching for mksquashfs: exec: "mksquashfs": executable file not found in $PATH. 

Thanks in advance, 
YP

**Comment by vsoch** [comment]
`mksquashfs` is a dependency of Singularity to create a SIF image. If you are running on a cluster you should see if it's loadable as a module (module spider squash) and either way, request from your linux admin to install it. If it is installed then the module file (or however singularity is loaded) needs to require it. If you are on your own machine, then just install for your platform based on the instructions: https://sylabs.io/guides/3.8/user-guide/quick_start.html?highlight=squashfs.

**Comment by yjp16GH** [comment]
Hi All, 

I've encountered a recent problem with singularity and thought you experts might be able to help. I successfully managed to pull the synb0 container from docker, however when trying to run the synb0.simg container I receive the following error:

FATAL: while extracting path-to-container/synb0_latest.sif: root filesystem extraction failed: extract command failed; ERROR :Failed to create user namespace: user namespace disabled

Does anyone have a solution? 

Thanks in advance, 
YP

**Comment by vsoch** [comment]
It has to do with your admin's setup of singularity. If you search for that error there are a lot of issues reporting the same. https://github.com/hpcng/singularity/issues/5240#issuecomment-618405898. I would read through those and then have a chat with whomever installed Singularity for you.

**Comment by schillkg** [comment]
Sounds like this was resolved. Closing for now.
