### ISSUE TITLE
/INPUTS/T1.nii.gz: No such file or directory

### ISSUE THREAD

**Issue by PriyankaAppMath** [MASILab/Synb0-DISCO#71]
Hello, I am naive to docker and 1st time using it. I used these commands 
 **sudo docker run --rm\
 -v /home/pc/Documents/research/test_subject/:/INPUTS/\
 -v /home/pc/Documents/research/test_subject/OUTPUTS:/OUTPUTS/\
 -v /usr/local//freesurfer/license.txt:/extra/freesurfer/license.txt\
 --user $(id -u):$(id -g) \
 leonyichencai/synb0-disco:v3.1**

I am getting lots of error
_-------
INPUTS:
Distorted b0 path: /INPUTS/b0.nii.gz
T1 path: /INPUTS/T1.nii.gz
T1 atlas path: /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c.nii.gz
T1 2.5 iso atlas path: /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c_2_5.nii.gz
Results path: /OUTPUTS
-------
Job directory path: /tmp/tmp.cA6jVQkVqw
-------
Making results directory...
-------
Normalizing T1
normalize_T1.sh /INPUTS/T1.nii.gz /tmp/tmp.cA6jVQkVqw/T1_N3.nii.gz /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz
-------
INPUTS:
T1 path: /INPUTS/T1.nii.gz
T1 N3 path: /tmp/tmp.cA6jVQkVqw/T1_N3.nii.gz
T1 normalized path: /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz
-------
Job directory path: /tmp/tmp.EusINjETyw
cp: cannot stat '/INPUTS/T1.nii.gz': No such file or directory
-------
mri_convert /tmp/tmp.EusINjETyw/T1.nii.gz /tmp/tmp.EusINjETyw/T1.mgz
mri_convert.bin /tmp/tmp.EusINjETyw/T1.nii.gz /tmp/tmp.EusINjETyw/T1.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /tmp/tmp.EusINjETyw/T1.nii.gz...
niiRead(): error opening file /tmp/tmp.EusINjETyw/T1.nii.gz
-------
mri_nu_correct.mni --i /tmp/tmp.EusINjETyw/T1.mgz --o /tmp/tmp.EusINjETyw/T1_N3.mgz --n 2
ERROR: input volume /tmp/tmp.EusINjETyw/T1.mgz does not exist
-------
mri_convert /tmp/tmp.EusINjETyw/T1_N3.mgz /tmp/tmp.cA6jVQkVqw/T1_N3.nii.gz
mri_convert.bin /tmp/tmp.EusINjETyw/T1_N3.mgz /tmp/tmp.cA6jVQkVqw/T1_N3.nii.gz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /tmp/tmp.EusINjETyw/T1_N3.mgz...
mghRead(/tmp/tmp.EusINjETyw/T1_N3.mgz, -1): could not open file
-------
mri_normalize -g 1 -mprage /tmp/tmp.EusINjETyw/T1_N3.mgz /tmp/tmp.EusINjETyw/T1_norm.mgz
using max gradient = 1.000
assuming input volume is MGH (Van der Kouwe) MP-RAGE
reading from /tmp/tmp.EusINjETyw/T1_N3.mgz...
mghRead(/tmp/tmp.EusINjETyw/T1_N3.mgz, -1): could not open file
mri_normalize: could not open source file /tmp/tmp.EusINjETyw/T1_N3.mgz
Permission denied
-------
mri_convert /tmp/tmp.EusINjETyw/T1_norm.mgz /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz
mri_convert.bin /tmp/tmp.EusINjETyw/T1_norm.mgz /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz 
mghRead(/tmp/tmp.EusINjETyw/T1_norm.mgz, -1): could not open file
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /tmp/tmp.EusINjETyw/T1_norm.mgz...
-------
Removing job directory...
-------
Skull stripping T1
bet /INPUTS/T1.nii.gz /tmp/tmp.cA6jVQkVqw/T1_mask.nii.gz -R

Error: input image /INPUTS/T1 not valid

-------
epi_reg distorted b0 to T1
epi_reg --epi=/INPUTS/b0.nii.gz --t1=/INPUTS/T1.nii.gz --t1brain=/tmp/tmp.cA6jVQkVqw/T1_mask.nii.gz --out=/tmp/tmp.cA6jVQkVqw/epi_reg_d
Running FAST segmentation
Image Exception : #63 :: No image files match: /tmp/tmp.cA6jVQkVqw/T1_mask
Image Exception : #22 :: Failed to read volume /tmp/tmp.cA6jVQkVqw/T1_mask
Error : No image files match: /tmp/tmp.cA6jVQkVqw/T1_mask
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to read volume /tmp/tmp.cA6jVQkVqw/T1_mask
Error : No image files match: /tmp/tmp.cA6jVQkVqw/T1_mask
/extra/fsl/bin/epi_reg: line 320:   275 Aborted                 (core dumped) $FSLDIR/bin/fast -o ${vout}_fast ${vrefbrain}
Image Exception : #63 :: No image files match: /tmp/tmp.cA6jVQkVqw/epi_reg_d_fast_pve_2
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /tmp/tmp.cA6jVQkVqw/epi_reg_d_fast_pve_2
/extra/fsl/bin/epi_reg: line 320:   276 Aborted                 (core dumped) $FSLDIR/bin/fslmaths ${vout}_fast_pve_2 -thr 0.5 -bin ${vout}_fast_wmseg
Image Exception : #63 :: No image files match: /tmp/tmp.cA6jVQkVqw/epi_reg_d_fast_wmseg
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /tmp/tmp.cA6jVQkVqw/epi_reg_d_fast_wmseg
FLIRT pre-alignment
/extra/fsl/bin/epi_reg: line 329:   301 Aborted                 (core dumped) $FSLDIR/bin/fslmaths ${vout}_fast_wmseg -edge -bin -mas ${vout}_fast_wmseg ${vout}_fast_wmedge
Image Exception : #63 :: No image files match: /tmp/tmp.cA6jVQkVqw/T1_mask
Image Exception : #22 :: Failed to read volume /tmp/tmp.cA6jVQkVqw/T1_mask
Error : No image files match: /tmp/tmp.cA6jVQkVqw/T1_mask
Failed to read volume /tmp/tmp.cA6jVQkVqw/T1_mask
Error : No image files match: /tmp/tmp.cA6jVQkVqw/T1_mask
Running BBR
Image Exception : #63 :: No image files match: /INPUTS/T1
Image Exception : #22 :: Failed to read volume /INPUTS/T1
Error : No image files match: /INPUTS/T1
Failed to read volume /INPUTS/T1
Error : No image files match: /INPUTS/T1
Could not open matrix file /tmp/tmp.cA6jVQkVqw/epi_reg_d.mat
Image Exception : #63 :: No image files match: /INPUTS/b0
Image Exception : #22 :: Failed to read volume /INPUTS/b0
Error : No image files match: /INPUTS/b0
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to read volume /INPUTS/b0
Error : No image files match: /INPUTS/b0
/extra/fsl/bin/epi_reg: line 399:   304 Aborted                 (core dumped) $FSLDIR/bin/applywarp -i ${vepi} -r ${vrefhead} -o ${vout} --premat=${vout}.mat --interp=spline
-------
converting FSL transform to ANTS transform
c3d_affine_tool -ref /INPUTS/T1.nii.gz -src /INPUTS/b0.nii.gz /tmp/tmp.cA6jVQkVqw/epi_reg_d.mat -fsl2ras -oitk /tmp/tmp.cA6jVQkVqw/epi_reg_d_ANTS.txt
Exception raised during processing:
/mnt/build/pauly/buildbot/Nightly/itk/v4.12.2/itk/Modules/IO/ImageBase/include/itkImageFileReader.hxx:143:
 Could not create IO object for reading file /INPUTS/T1.nii.gz
The file doesn't exist. 
Filename = /INPUTS/T1.nii.gz

-------
ANTS syn registration
antsRegistrationSyNQuick.sh -d 3 -f /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c.nii.gz -m /INPUTS/T1.nii.gz -o /tmp/tmp.cA6jVQkVqw/ANTS
Moving image '/INPUTS/T1.nii.gz' does not exist.  See usage: '/extra/ANTS/ANTs/Scripts/antsRegistrationSyNQuick.sh -h 1'
-------
Apply linear transform to T1
antsApplyTransforms -d 3 -i /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz -r /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c_2_5.nii.gz -n BSpline -t /tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat -o /tmp/tmp.cA6jVQkVqw/T1_norm_lin_atlas_2_5.nii.gz
 file /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz does not exist . 
Transform file does not exist: /tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat
-------
Apply linear transform to distorted b0
antsApplyTransforms -d 3 -i /INPUTS/b0.nii.gz -r /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c_2_5.nii.gz -n BSpline -t /tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat -t /tmp/tmp.cA6jVQkVqw/epi_reg_d_ANTS.txt -o /tmp/tmp.cA6jVQkVqw/b0_d_lin_atlas_2_5.nii.gz
 file /INPUTS/b0.nii.gz does not exist . 
Transform file does not exist: /tmp/tmp.cA6jVQkVqw/epi_reg_d_ANTS.txt
-------
Apply nonlinear transform to T1
antsApplyTransforms -d 3 -i /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz -r /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c_2_5.nii.gz -n BSpline -t /tmp/tmp.cA6jVQkVqw/ANTS1Warp.nii.gz -t /tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat -o /tmp/tmp.cA6jVQkVqw/T1_norm_nonlin_atlas_2_5.nii.gz
 file /tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz does not exist . 
Transform file does not exist: /tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat
-------
Apply nonlinear transform to distorted b0
antsApplyTransforms -d 3 -i /INPUTS/b0.nii.gz -r /extra/atlases/mni_icbm152_t1_tal_nlin_asym_09c_2_5.nii.gz -n BSpline -t /tmp/tmp.cA6jVQkVqw/ANTS1Warp.nii.gz -t /tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat -t /tmp/tmp.cA6jVQkVqw/epi_reg_d_ANTS.txt -o /tmp/tmp.cA6jVQkVqw/b0_d_nonlin_atlas_2_5.nii.gz
 file /INPUTS/b0.nii.gz does not exist . 
Transform file does not exist: /tmp/tmp.cA6jVQkVqw/epi_reg_d_ANTS.txt
-------
Copying results to results path...
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/T1_norm.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/T1_mask.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/epi_reg_d.mat': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/epi_reg_d_ANTS.txt': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/ANTS0GenericAffine.mat': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/ANTS1Warp.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/ANTS1InverseWarp.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/T1_norm_lin_atlas_2_5.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/T1_norm_nonlin_atlas_2_5.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/b0_d_lin_atlas_2_5.nii.gz': No such file or directory
cp: cannot stat '/tmp/tmp.cA6jVQkVqw/b0_d_nonlin_atlas_2_5.nii.gz': No such file or directory
-------
Removing job directory...
Performing inference on FOLD: 1
T1 input path: /OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz
b0 input path: /OUTPUTS/b0_d_lin_atlas_2_5.nii.gz
b0 output path: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_1.nii.gz
Model path: /extra/dual_channel_unet/num_fold_1_total_folds_5_seed_1_num_epochs_100_lr_0.0001_betas_(0.9, 0.999)_weight_decay_1e-05_num_epoch_97.pth
Traceback (most recent call last):
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/extra/inference.py", line 90, in <module>
    img_model = inference(T1_input_path, b0_input_path, model, device)
  File "/extra/inference.py", line 31, in inference
    img_T1 = np.expand_dims(util.get_nii_img(T1_path), axis=3)
  File "/extra/util.py", line 24, in get_nii_img
    nii = nib.load(path_nii)
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'
Performing inference on FOLD: 2
T1 input path: /OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz
b0 input path: /OUTPUTS/b0_d_lin_atlas_2_5.nii.gz
b0 output path: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_2.nii.gz
Model path: /extra/dual_channel_unet/num_fold_2_total_folds_5_seed_1_num_epochs_100_lr_0.0001_betas_(0.9, 0.999)_weight_decay_1e-05_num_epoch_98.pth
Traceback (most recent call last):
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/extra/inference.py", line 90, in <module>
    img_model = inference(T1_input_path, b0_input_path, model, device)
  File "/extra/inference.py", line 31, in inference
    img_T1 = np.expand_dims(util.get_nii_img(T1_path), axis=3)
  File "/extra/util.py", line 24, in get_nii_img
    nii = nib.load(path_nii)
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'
Performing inference on FOLD: 3
T1 input path: /OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz
b0 input path: /OUTPUTS/b0_d_lin_atlas_2_5.nii.gz
b0 output path: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_3.nii.gz
Model path: /extra/dual_channel_unet/num_fold_3_total_folds_5_seed_1_num_epochs_100_lr_0.0001_betas_(0.9, 0.999)_weight_decay_1e-05_num_epoch_90.pth
Traceback (most recent call last):
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/extra/inference.py", line 90, in <module>
    img_model = inference(T1_input_path, b0_input_path, model, device)
  File "/extra/inference.py", line 31, in inference
    img_T1 = np.expand_dims(util.get_nii_img(T1_path), axis=3)
  File "/extra/util.py", line 24, in get_nii_img
    nii = nib.load(path_nii)
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'
Performing inference on FOLD: 4
T1 input path: /OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz
b0 input path: /OUTPUTS/b0_d_lin_atlas_2_5.nii.gz
b0 output path: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_4.nii.gz
Model path: /extra/dual_channel_unet/num_fold_4_total_folds_5_seed_1_num_epochs_100_lr_0.0001_betas_(0.9, 0.999)_weight_decay_1e-05_num_epoch_90.pth
Traceback (most recent call last):
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/extra/inference.py", line 90, in <module>
    img_model = inference(T1_input_path, b0_input_path, model, device)
  File "/extra/inference.py", line 31, in inference
    img_T1 = np.expand_dims(util.get_nii_img(T1_path), axis=3)
  File "/extra/util.py", line 24, in get_nii_img
    nii = nib.load(path_nii)
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'
Performing inference on FOLD: 5
T1 input path: /OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz
b0 input path: /OUTPUTS/b0_d_lin_atlas_2_5.nii.gz
b0 output path: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_5.nii.gz
Model path: /extra/dual_channel_unet/num_fold_5_total_folds_5_seed_1_num_epochs_100_lr_0.0001_betas_(0.9, 0.999)_weight_decay_1e-05_num_epoch_88.pth
Traceback (most recent call last):
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/extra/inference.py", line 90, in <module>
    img_model = inference(T1_input_path, b0_input_path, model, device)
  File "/extra/inference.py", line 31, in inference
    img_T1 = np.expand_dims(util.get_nii_img(T1_path), axis=3)
  File "/extra/util.py", line 24, in get_nii_img
    nii = nib.load(path_nii)
  File "/extra/pytorch/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/OUTPUTS/T1_norm_lin_atlas_2_5.nii.gz'
Taking ensemble average
Image Exception : #63 :: No image files match: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_*
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_*
/extra/pipeline.sh: line 49:   645 Aborted                 (core dumped) fslmerge -t /OUTPUTS/b0_u_lin_atlas_2_5_merged.nii.gz /OUTPUTS/b0_u_lin_atlas_2_5_FOLD_*.nii.gz
Image Exception : #63 :: No image files match: /OUTPUTS/b0_u_lin_atlas_2_5_merged
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /OUTPUTS/b0_u_lin_atlas_2_5_merged
/extra/pipeline.sh: line 50:   646 Aborted                 (core dumped) fslmaths /OUTPUTS/b0_u_lin_atlas_2_5_merged.nii.gz -Tmean /OUTPUTS/b0_u_lin_atlas_2_5.nii.gz
Applying inverse xform to undistorted b0
 file /OUTPUTS/b0_u_lin_atlas_2_5.nii.gz does not exist . 
 file /INPUTS/b0.nii.gz does not exist . 
Transform file does not exist: /OUTPUTS/ANTS0GenericAffine.mat
Applying slight smoothing to distorted b0
Image Exception : #63 :: No image files match: /INPUTS/b0
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /INPUTS/b0
/extra/pipeline.sh: line 58:   648 Aborted                 (core dumped) fslmaths /INPUTS/b0.nii.gz -s 1.15 /OUTPUTS/b0_d_smooth.nii.gz
Running topup
Image Exception : #63 :: No image files match: /OUTPUTS/b0_d_smooth
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /OUTPUTS/b0_d_smooth
/extra/pipeline.sh: line 65:   649 Aborted                 (core dumped) fslmerge -t /OUTPUTS/b0_all.nii.gz /OUTPUTS/b0_d_smooth.nii.gz /OUTPUTS/b0_u.nii.gz
Could not open matrix file /INPUTS/acqparams.txt
_

Could anyone help.

**Comment by schillkg** [comment]
The docker cannot find your T1.nii.gz image. Double check to be sure you are pointing to the correct directory. That is the first step in the process, if it cannot find a T1 all other steps will fail.

**Comment by PriyankaAppMath** [comment]
Thank you. I changed the path and it ran.
